FROM jenkins/jenkins:lts
USER root
# 安装所需的工具
RUN apt-get update \
  && apt-get install -y sudo \
  && rm -rf /var/lib/apt/lists/*
# 配置Jenkins权限
RUN echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER jenkins