/*
 * This file was automatically generated by EvoSuite
 * Sat May 20 08:44:03 GMT 2023
 */

package com.jupiter.calc;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jupiter.calc.Say;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Say_ESTest extends Say_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Say say0 = new Say();
      say0.sayHappy();
  }
}
