version: '3.9'

networks:
  wp_net:
    driver: bridge

services:
  wpadmin:
    image: ${REPO_URL}/world-peace-admin:1.0
    mem_limit: 200m
    user: "0:0" #run with root user (UID:GID)
    container_name: wpadmin
    hostname: wpadmin
    ports:
      - "80:8090"
    volumes:
      - ${PERSIST_PATH}/wpadmin/logs:/logs/admin
      - ${PERSIST_PATH}/wpadmin/data:/usr/apps/wp/data
    networks:
      wp_net:
        aliases:
          - wpadmin
  wpapi:
    image: world-peace-api:1.0
    user: "0:0" #run with root user (UID:GID)
    container_name: wpapi
    hostname: wpapi
    networks:
      wp_net:
        aliases:
          - wpapi
    ports:
      - "8081:8081"
    volumes:
      - ${PERSIST_PATH}/wpapi/logs:/logs/api
  wppoc:
    image: world-peace-poc:1.0
    user: "0:0"
    container_name: wppoc
    hostname: wppoc
    networks:
      wp_net:
        aliases:
          - wppoc
    ports:
      - "18080:8080"
    volumes:
      - ${PERSIST_PATH}/wppoc/logs:/logs/poc

